// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_yIRebMPEibgrNqpTdUNDS1lTQyVspM',
    appId: '1:597609823578:web:3cbfee7d2a429b14ad8763',
    messagingSenderId: '597609823578',
    projectId: 'reddit-clone-eef6c',
    authDomain: 'reddit-clone-eef6c.firebaseapp.com',
    storageBucket: 'reddit-clone-eef6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRdiJ-oNst6fnG3tHmlufYGsQ0mTE1MYQ',
    appId: '1:597609823578:android:165596d4a9c50bf7ad8763',
    messagingSenderId: '597609823578',
    projectId: 'reddit-clone-eef6c',
    storageBucket: 'reddit-clone-eef6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbJLb1ZKkiQCCZQNi7UqiNlZGnQFaO2-U',
    appId: '1:597609823578:ios:1c1ff1175d3b2327ad8763',
    messagingSenderId: '597609823578',
    projectId: 'reddit-clone-eef6c',
    storageBucket: 'reddit-clone-eef6c.appspot.com',
    iosClientId: '597609823578-0nccfotptniv7slhlt60rr17japl1258.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbJLb1ZKkiQCCZQNi7UqiNlZGnQFaO2-U',
    appId: '1:597609823578:ios:1c1ff1175d3b2327ad8763',
    messagingSenderId: '597609823578',
    projectId: 'reddit-clone-eef6c',
    storageBucket: 'reddit-clone-eef6c.appspot.com',
    iosClientId: '597609823578-0nccfotptniv7slhlt60rr17japl1258.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
